services:
  postgres:
    image: postgres:16
    container_name: accounting-postgres
    environment:
      POSTGRES_DB: accounting
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mkdocs:
    build:
      context: .
      dockerfile: ./docs/Dockerfile
    environment:
        PLANTUML_SERVER_URL: http://plantuml:8080/plantuml
    volumes:
      - ./docs:/docs/docs
      - ./README.md:/docs/README.md
      - ./mkdocs.yml:/docs/mkdocs.yml
      - ./site:/docs/site
    ports:
      - "8000:8000"
    command: mkdocs serve --dev-addr=0.0.0.0:8000 --livereload
    links:
      - plantuml

  plantuml:
    image: plantuml/plantuml-server:jetty
    environment:
      BASE_URL: plantuml

volumes:
  postgres_data:
